import {
  Cpu,
  Cog,
  Building2,
  Zap,
  FlaskConical,
  Factory,
  Plane,
  Heart,
  Leaf,
  Droplets,
  Gem,
  Radiation,
  Ship,
  Mountain,
  Bot,
  Car,
  Home,
  Radio,
  Pickaxe,
  Wheat,
  Lightbulb,
  Volume2,
  Microscope,
} from "lucide-react"

export const engineeringDisciplines = [
  { name: "Software Engineer", icon: Cpu, color: "bg-blue-500" },
  { name: "Mechanical Engineer", icon: Cog, color: "bg-gray-500" },
  { name: "Civil Engineer", icon: Building2, color: "bg-orange-500" },
  { name: "Electrical Engineer", icon: Zap, color: "bg-yellow-500" },
  { name: "Computer Engineer", icon: Cpu, color: "bg-purple-500" },
  { name: "Chemical Engineer", icon: FlaskConical, color: "bg-green-500" },
  { name: "Industrial Engineer", icon: Factory, color: "bg-red-500" },
  { name: "Aerospace Engineer", icon: Plane, color: "bg-sky-500" },
  { name: "Biomedical Engineer", icon: Heart, color: "bg-pink-500" },
  { name: "Environmental Engineer", icon: Leaf, color: "bg-emerald-500" },
  { name: "Petroleum Engineer", icon: Droplets, color: "bg-amber-600" },
  { name: "Materials Engineer", icon: Gem, color: "bg-violet-500" },
  { name: "Nuclear Engineer", icon: Radiation, color: "bg-lime-500" },
  { name: "Marine Engineer", icon: Ship, color: "bg-cyan-500" },
  { name: "Geotechnical Engineer", icon: Mountain, color: "bg-stone-500" },
  { name: "Robotics Engineer", icon: Bot, color: "bg-indigo-500" },
  { name: "Automotive Engineer", icon: Car, color: "bg-rose-500" },
  { name: "Structural Engineer", icon: Home, color: "bg-teal-500" },
  { name: "Telecommunications Engineer", icon: Radio, color: "bg-fuchsia-500" },
  { name: "Mining Engineer", icon: Pickaxe, color: "bg-yellow-600" },
  { name: "Agricultural Engineer", icon: Wheat, color: "bg-green-600" },
  { name: "Photonics Engineer", icon: Lightbulb, color: "bg-orange-400" },
  { name: "Acoustical Engineer", icon: Volume2, color: "bg-blue-600" },
  { name: "Nanoengineer", icon: Microscope, color: "bg-purple-600" },
]

export const topUniversities = [
  "Stanford University",
  "Harvard University",
  "MIT",
  "Caltech",
  "Oxford University",
  "Cambridge University",
  "ETH Zurich",
  "University of Tokyo",
  "Tsinghua University",
  "American University of Sharjah",
  "University of Toronto",
  "Universidad Politécnica de Madrid",
  "Technical University of Munich",
  "École Polytechnique",
  "Politecnico di Milano",
  "Imperial College London",
]

export const countries = [
  "USA",
  "Canada",
  "Spain",
  "Germany",
  "France",
  "Italy",
  "UK",
  "Japan",
  "China",
  "UAE",
  "Switzerland",
  "Australia",
  "Netherlands",
  "Sweden",
  "South Korea",
  "Singapore",
  "Brazil",
  "India",
  "Russia",
  "Norway",
] 